spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: aegiron-auth
          uri: lb://aegiron-auth
          predicates:
            - Path=/aegiron-auth/**
          filters:
            - StripPrefix=1
        - id: aegiron-system
          uri: lb://aegiron-system
          predicates:
            - Path=/aegiron-system/**
          filters:
            - StripPrefix=1